services:
  producer:
    image: yt-crawler-producer:latest
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - kafka
  consumer:
    image: yt-crawler-consumer:latest
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - kafka
  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    ports:
      - 9092:9092
    command:
      - redpanda
      - start
      - --kafka-addr internal://kafka:9092,external://127.0.0.1:19092
      - --advertise-kafka-addr internal://kafka:9092,external://127.0.0.1:9092
      - --smp 1
      - --mode dev-container
